# the-diabetic-compass (tdc)
version: "3.8"
services:
  # database service
  db:
    container_name: tdc-db
    restart: always
    image: mysql:8
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
